# Generated by Django 2.1.2 on 2018-10-10 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid10', models.CharField(max_length=8)),
                ('descricao', models.TextField(null=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='atendimento.Atendimento')),
            ],
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('resultado', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('dose', models.FloatField()),
                ('posologia', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamentos', to='atendimento.Atendimento')),
            ],
        ),
        migrations.AddField(
            model_name='procedimento',
            name='tratamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos', to='atendimento.Tratamento'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='tratamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='atendimento.Tratamento'),
        ),
        migrations.AddField(
            model_name='exame',
            name='tratamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='atendimento.Tratamento'),
        ),
    ]
